version: '3'
services:
  app:
    build: ./phpfpm72
    volumes:
      - ../public:/var/www/html
    container_name: app

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ../public:/var/www/html
      - ../logs/nginx:/var/log/nginx
    container_name: nginx
