version: '3'
services:
  app:
    build: ./phpfpm72
    depends_on:
      - db
    volumes:
      - ../application:/var/www/html
    container_name: app

  cli:
    build: ./phpfpm72
    volumes:
      - ../application:/var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    container_name: cli

  composer:
    image: composer:latest
    volumes:
      - ../application:/application
    working_dir: /application
    container_name: composer

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ../logs/nginx:/var/log/nginx
    container_name: nginx

  db:
    build: ./mysql
    ports:
      - "13306:3306"
    env_file: .env.develop
    volumes:
      - ../data/mysql:/var/lib/mysql
      - ../logs/mysql:/var/log/mysql
    container_name: db

  cache:
    build: ./redis
    ports:
      - "16379:6379"
    volumes:
      - ../data/redis:/data
    container_name: cache
